% Postprocess the data
close all
clear all

% Mu-Metal :
%               Expensive, high permeability
%               sigma = 1.61e+06 [1/(ohm.m)]   
%               mu_r = 50000 
%               Price/m^3 = 3e+06 $ 

% AK Steel 400 :
%               is one of the most economical chromium ferritic stainless steels
%               sigma = 1.66e+06 [1/(ohm.m)] 
%               mu_r = 1800 
%               Price/m^3 = 

% Medium grade Carbon Steel :
%               Expensive, high permeability
%               sigma = 6.02e+06 [1/(ohm.m)]
%               mu_r = 100  
%               Price/m^3 = 7785.63$



%% Influence of l_shield
l=[2 4 6 8 10];
for i=1:5
DATA.muMetal(:,:,i) = load(strcat('../magnetic/results/b_line_muMetal_l',num2str(l(i)),'.txt'))
DATA.FerriticSteinlessSteel(:,:,i) = load(strcat('../magnetic/results/b_line_FerriticSteinlessSteel_l',num2str(l(i)),'.txt'))
DATA.CarbonSteel(:,:,i) = load(strcat('../magnetic/results/b_line_CarbonSteel_l',num2str(l(i)),'.txt'))
end

MeasurementPoint = 50; % x=0, y=-4.05, z=0
 
figure(1)
hold on
plot(l,...
             reshape(max(sqrt( DATA.muMetal(:,9,:).^2 +...
             DATA.muMetal(:,10,:).^2 +...
             DATA.muMetal(:,11,:).^2)),[1,5]), 'linewidth',2)
plot(l,...
             reshape(max(sqrt( DATA.FerriticSteinlessSteel(:,9,:).^2 +...
             DATA.FerriticSteinlessSteel(:,10,:).^2 + ...
             DATA.FerriticSteinlessSteel(:,11,:).^2)),[1,5]), 'linewidth',2)
plot(l,...
             reshape(max(sqrt( DATA.CarbonSteel(:,9,:).^2 +...
             DATA.CarbonSteel(:,10,:).^2 +...
             DATA.CarbonSteel(:,11,:).^2)),[1,5]), 'linewidth',2)
         
plot(l,...
             reshape(sqrt( DATA.muMetal(MeasurementPoint,9,:).^2 +...
             DATA.muMetal(MeasurementPoint,10,:).^2 +...
             DATA.muMetal(MeasurementPoint,11,:).^2),[1,5]))
plot(l,...
             reshape(sqrt( DATA.FerriticSteinlessSteel(MeasurementPoint,9,:).^2 +...
             DATA.FerriticSteinlessSteel(MeasurementPoint,10,:).^2 + ...
             DATA.FerriticSteinlessSteel(MeasurementPoint,11,:).^2),[1,5]))
plot(l,...
             reshape(sqrt( DATA.CarbonSteel(MeasurementPoint,9,:).^2 +...
             DATA.CarbonSteel(MeasurementPoint,10,:).^2 +...
             DATA.CarbonSteel(MeasurementPoint,11,:).^2),[1,5]))
         
xlabel('$l_{shield}$ [m]','interpreter', 'latex')
ylabel('$\| \!R \{ \textbf{B}\} \|$[T]', 'interpreter', 'latex')
legend('mu-metal (max)', 'Ferritic Stainless Steel (max)', 'Carbon Steel (max)', 'mu-metal (centered)', 'Ferritic Stainless Steel (centered)', 'Carbon Steel (centered)')
grid on
hold off



%% Influence of t_shield
t=[1 2 3 4 5];
for i=1:5
DATA.muMetal(:,:,i) = load(strcat('../magnetic/results/b_line_muMetal_t',num2str(t(i)),'.txt'))
DATA.FerriticSteinlessSteel(:,:,i) = load(strcat('../magnetic/results/b_line_FerriticSteinlessSteel_t',num2str(t(i)),'.txt'))
DATA.CarbonSteel(:,:,i) = load(strcat('../magnetic/results/b_line_CarbonSteel_t',num2str(t(i)),'.txt'))
end

MeasurementPoint = 50; % x=0, y=-4.05, z=0

figure(2)
hold on
plot(t,...
             reshape(max(sqrt( DATA.muMetal(:,9,:).^2 +...
             DATA.muMetal(:,10,:).^2 +...
             DATA.muMetal(:,11,:).^2)),[1,5]), 'linewidth',2)
plot(t,...
             reshape(max(sqrt( DATA.FerriticSteinlessSteel(:,9,:).^2 +...
             DATA.FerriticSteinlessSteel(:,10,:).^2 + ...
             DATA.FerriticSteinlessSteel(:,11,:).^2)),[1,5]), 'linewidth',2)
plot(t,...
             reshape(max(sqrt( DATA.CarbonSteel(:,9,:).^2 +...
             DATA.CarbonSteel(:,10,:).^2 +...
             DATA.CarbonSteel(:,11,:).^2)),[1,5]), 'linewidth',2)
         
plot(t,...
             reshape(sqrt( DATA.muMetal(MeasurementPoint,9,:).^2 +...
             DATA.muMetal(MeasurementPoint,10,:).^2 +...
             DATA.muMetal(MeasurementPoint,11,:).^2),[1,5]))
plot(t,...
             reshape(sqrt( DATA.FerriticSteinlessSteel(MeasurementPoint,9,:).^2 +...
             DATA.FerriticSteinlessSteel(MeasurementPoint,10,:).^2 + ...
             DATA.FerriticSteinlessSteel(MeasurementPoint,11,:).^2),[1,5]))
plot(t,...
             reshape(sqrt( DATA.CarbonSteel(MeasurementPoint,9,:).^2 +...
             DATA.CarbonSteel(MeasurementPoint,10,:).^2 +...
             DATA.CarbonSteel(MeasurementPoint,11,:).^2),[1,5]))
         
xlabel('$t_{shield}$ [mm]','interpreter', 'latex')
ylabel('$\| \!R \{ \textbf{B}\} \|$[T]', 'interpreter', 'latex')
legend('mu-metal (max)', 'Ferritic Stainless Steel (max)', 'Carbon Steel (max)', 'mu-metal (centered)', 'Ferritic Stainless Steel (centered)', 'Carbon Steel (centered)')
grid on
hold off